version: "3.8"

services:
  zomboid-dedicated-server:
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
    image: "ghcr.io/loretdemolas/pz-server:master"
    container_name: zomboid-dedicated-server
    restart: unless-stopped
    environment:
      - "ADMIN_PASSWORD=changeme"
      - "ADMIN_USERNAME=superuser"
      - "AUTOSAVE_INTERVAL=15"
      - "BIND_IP=0.0.0.0"
      - "DEFAULT_PORT=16261"
      - "GAME_VERSION=public"
      - "GC_CONFIG=ZGC"
      - "MAP_NAMES=Muldraugh, KY"
      - "MAX_PLAYERS=16"
      - "MAX_RAM=4096m"
      - "MOD_NAMES="
      - "MOD_WORKSHOP_IDS="
      - "PAUSE_ON_EMPTY=true"
      - "PUBLIC_SERVER=true"
      - "RCON_PASSWORD=changeme_rcon"
      - "RCON_PORT=27015"
      - "SERVER_NAME=ZomboidServer"
      - "SERVER_PASSWORD="
      - "STEAM_VAC=true"
      - "UDP_PORT=16262"
      - "USE_STEAM=true"
      - "TZ=UTC"
    ports:
      - target: 16261
        published: 16261
        protocol: udp
      - target: 16262 - 16272
        published: 16262 -16272
        protocol: udp
      - target: 27015
        published: 27015
        protocol: tcp
    volumes:
      - type: volume
        source: ZomboidDedicatedServer
        target: /home/steam/ZomboidDedicatedServer
      - type: volume
        source: ZomboidConfig
        target: /home/steam/Zomboid/
    tty: true
    stdin_open: true 
    networks:
      - network1
volumes:
  ZomboidDedicatedServer:
    external: true
  ZomboidConfig:
    external: true
networks:
  network1:
    name: GameServer
    external: true
