version: "3.8"

services:
  zomboid-dedicated-server:
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    image: "ghcr.io/loretdemolas/pz-server:master"
    container_name: zomboid-dedicated-server
    restart: unless-stopped
    environment:
      - "ADMIN_PASSWORD=Seba5054.."
      - "ADMIN_USERNAME=Bobs Your Uncle"
      - "AUTOSAVE_INTERVAL=5"
      - "BIND_IP=0.0.0.0"
      - "DEFAULT_PORT=16261"
      - "GAME_VERSION=public"
      - "GC_CONFIG=ZGC"
      - "MAP_NAMES=Muldraugh, KY"
      - "MAX_PLAYERS=10"
      - "MAX_RAM=8000m"
      - "MOD_NAMES=93lorevehiclepack;67commando;84merc;85merc;86oshkoshP19A;ADRENALINE_MOD;AFTAA;AntiqueArmarment;Arsenal(26)GunFighter;modoptions;Brita;BCGRareWeapons;BCGTools;CDCRapidResponse;CDCRapidResponseSettingsNoHope;BB_CommonSense;DRAW_ON_MAP;KADropnLoot;ExtraMapSymbols;ExtraMapSymbolsUI;FRUsedCarsNLF;FRUsedCarsNRN;FRUsedCars;FRUsedCarsFT;P4HasBeenRead;ItemTweakerAPI;ItemTweakerAPIExtraClothingAddon;LamboDiablofhq;MapLegendUI;MapSymbolSizeSlider;MinimalDisplayBars;mod_loader;moodle_quarters;OutTheWindow;QNW_QNWLibrary;RainWash;RewardingNightCombat;RotatorsLib;SkillRecoveryJournal;SpnOpenCloth;TMC_TrueActions;tsarslib;rSemiTruck;rWaterTrailer;TheStar;WeaponModifiersExtensive;WeaponModifiersFramework;WeaponModifiersRealistic;WeaponModifiersReforge;Weapon Sound Expansions;wringclothesnostr;QNW_Ladder;GEARBASIC;GEARCORE;sleepingbagsandattachments;bikinitools;82oshkoshM911;rWaterTrailerSemi;Improved_Muzzle_Flash;ImprovisedSilencers;Insurgent;InsurgentBRITAWEAPONS;InsurgentEXMILITARY;BecomeDesensitized;HordeNight01;AcceleratingZombies;FactionMap;ReloadAllMagazines;FuelAPI;fuelsideindicator;MWR;MoreLockManagementSA;ProximityInventory;ProximityInventoryZombonly;WorkingMasks;addInteriorLock;Simplesling;Brita_2;NVAPI;NVG;KeepBuildingsPrincipalDoorsLockableWithoutKey"
      - "MOD_WORKSHOP_IDS=2809058492;2478247379;2805630347;2469388752;2566953935;2807001835;2781774668;2926802017;2297098490;2169435993;2200148440;2432621382;2423906082;2857296919;2869308545;2875848298;2804531012;2871469707;2701170568;1510950729;2544353492;566115016;2810800927;2767472803;2710167561;2734705913;2004998206;2903176233;2854030563;2659216714;2845810596;2657661246;2781963981;2732594572;2503622437;2812326159;2487022075;2392709985;2759339330;2732639855;2619072426;2932853467;2872574857;2724435363;2862018814;2048411289;2747565374;2634426926;2618213077;2644648425;2799742455;2907683021;2627877543;2714850307;2842158398;2747261527;2877685881;2920899878;2890558515;2688538916;2616986064;2874279665;2847184718;2760742937;2811440552;2868394326;2460154811;2776633989;2769995104"
      - "PAUSE_ON_EMPTY=true"
      - "PUBLIC_SERVER=true"
      - "RCON_PASSWORD=Seba5054!!"
      - "RCON_PORT=27015"
      - "SERVER_NAME=servertest"
      - "SERVER_PASSWORD="
      - "STEAM_VAC=true"
      - "UDP_PORT=16262"
      - "USE_STEAM=true"
      - "TZ=UTC"
      - "RESETID=4017086"
    ports:
      - target: 16261
        published: 16261
        protocol: udp
      - target: 16262
        published: 16262
        protocol: udp
      - target: 16263
        published: 16263
        protocol: udp
      - target: 16264
        published: 16264
        protocol: udp
      - target: 16265
        published: 16265
        protocol: udp
      - target: 16266
        published: 16266
        protocol: udp
      - target: 16267
        published: 16267
        protocol: udp
      - target: 16268
        published: 16268
        protocol: udp
      - target: 16269
        published: 16269
        protocol: udp
      - target: 16270
        published: 16270
        protocol: udp
      - target: 16271
        published: 16271
        protocol: udp
      - target: 27015
        published: 27015
        protocol: tcp
    volumes:
      - type: volume
        source: ZomboidDedicatedServer
        target: /home/steam/ZomboidDedicatedServer
      - type: volume
        source: ZomboidConfig
        target: /home/steam/Zomboid/
      - type: volume
        source: steamCMD
        target: /home/steam/.local/
      - type: volume
        source: steam
        target: /home/steam/Steam/
    tty: true
    stdin_open: true 
    networks:
      - network1
volumes:
  ZomboidDedicatedServer:
    external: true
  ZomboidConfig:
    external: true
  steamCMD:
    external: true
  steam:
    external: true
  
networks:
  network1:
    name: GameServer
    external: true
